version: "3.0"
services:
  lab:
    build:
      context: ./lab
    tty: true
    stdin_open: true
    ports:
      - "2222:22"
    networks:
      maqueta:
        ipv4_address: 172.20.0.100
  frontend:
    image: nginx
    volumes:
      - ./frontend/frontend/build:/usr/share/nginx/html:ro
    ports:
      - "3000:80"
    networks:
      maqueta:
        ipv4_address: 172.20.0.2
  web:
    build:
      context: ./web
    tty: true
    stdin_open: true
    dns:
      - 172.20.0.4
    volumes:
      - ./web/root_folder:/var/www/html
    networks:
      maqueta:
        ipv4_address: 172.20.0.3
  dns:
    build:
      context: ./dns
    tty: true
    stdin_open: true
    networks:
      maqueta:
        ipv4_address: 172.20.0.4
# vyos:
#   environment:
#     - BUILD_DATE=20200917
#     - VYOS_VERSION=version
#     - DEBIAN_VERSION=stable
#   build:
#     context: ./vyos
#     dockerfile: docker-vyos/Dockerfile
#   privileged: true
#   volumes:
#     - /lib/modules:/lib/modules
#     - ./vyos/prueba_config:/config
#   networks:
#     maqueta:
#       ipv4_address: 172.20.0.5
  validator:
    build:
      context: ./validator/runtime
    tty: true
    stdin_open: true
    ports:
      - "5000:5000"
    dns:
      - 172.20.0.4
    volumes:
      - ./validator:/app
    networks:
      maqueta:
        ipv4_address: 172.20.0.6

networks:
  maqueta:
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 172.20.0.0/24
